### PR TITLE
prefer the newer unittest.mock from the standard library when available

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by davesteele** [comment]
I appreciate this submission.

There is no need for the conditionals. All supported Python versions have the package. You can rework the pull if you like, or else I'm fine with doing it.

I fixed the obsolete call that precipitated this.

**Comment by a-detiste** [comment]
Hi, I mon Holliday this extended week-end. I ll check again on Tuesday.

**Comment by a-detiste** [comment]
I rebased

**Comment by davesteele** [comment]
Looks good. Thanks.

**Pull request merged**
