### PR TITLE
Prettified webpages with UIKIT.

### PR DESCRIPTION
**Pull request by krebbi**

### CODE REVIEW

**Comment by davesteele** [comment]
That's pretty extensive. It will be a week or so before I can really look at this.

**Comment by krebbi** [comment]
any news on this one?

**Comment by davesteele** [comment]
Looks good. Thanks.

**Comment by krebbi** [comment]
you're welcome.

**Comment by davesteele** [comment]
This is compiled source. How do I regenerate e.g. uikit-icons.js?

**Comment by krebbi** [comment]
https://github.com/uikit/uikit

**Pull request merged**
